# Generated by Django 3.1.7 on 2021-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.CharField(max_length=100, verbose_name='Mon')),
                ('tue', models.CharField(max_length=100, verbose_name='Tue')),
                ('wed', models.CharField(max_length=100, verbose_name='Wed')),
                ('thu', models.CharField(max_length=100, verbose_name='Thu')),
                ('fri', models.CharField(max_length=100, verbose_name='Fri')),
                ('sat', models.CharField(max_length=100, verbose_name='Sat')),
                ('sun', models.CharField(max_length=100, verbose_name='Sun')),
            ],
        ),
    ]
