# Generated by Django 3.1.7 on 2021-03-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_schedulefile_customer_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulefile',
            name='customer_letter',
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Schedule file'),
        ),
    ]
