# Generated by Django 3.1.7 on 2021-03-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210304_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Schedule file'),
        ),
    ]
